version: "3.9"
services:
  __container__-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/__container__-debug:${TAG}
    ports:
      - 2229:2229
      - 9229:9229
      - 9230:9230
      - 9231:9231

  __container__:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}__container__:${TAG}
    ports:
      - 3000:3000
